### ISSUE TITLE
Morning session peer-to-peer code review day 4

### ISSUE THREAD

**Issue by UsirusenIkon** [AbayomiOlaoye/Youth-In-Tech-Project#5]
### Hi @AbayomiOlaoye  :wave: 
**You have done great efforts to make this project we find that your project is :+1:** 

- [ ] Project Working Fine
- [ ] Nice Design 
- [ ] Linters are Passed 
- [ ] Proper Github flow
- [ ] Professional README file 

**But there is something that needs to improve :dart: we would like to suggest you, please**

- [ ]  Add a screenshot of mobile and pc on your readme file.

**Comment by AbayomiOlaoye** [comment]
Thanks for the guide, @UsirusenIkon. I shall work on that.
