### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by samuelmoiwa** [AbayomiOlaoye/Youth-In-Tech-Project#7]
# *Status: Required Changes* :recycle: 

Hi @AbayomiOlaoye  

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Top Highlight

-   No linter errors. :heavy_check_mark: 
-   Adherence to GitHub Flow. :heavy_check_mark: 
-   Great UI for the project. :heavy_check_mark: 
-   Meaningful commit messages. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

- [ ] Great job for pushing it this far. You've done pretty well on this project and I must commend you for that. :tada: . However, there are few things you need to work on before your project could be due for approval.
- [ ] I think base on the requirement the  Live Presentation Video Link in the readme file is supposed to be in the PR write up.

**Comment by AbayomiOlaoye** [comment]
Alright, thanks.
